namespace :voice_base do
  # Usage: rake voice_base:import_transcripts['oral-history']
  desc 'Import transcripts generated by VoiceBase'
  task :import_transcripts, [:project_key] => :environment do |task, args|
    VoiceBase::ImportSrtTranscripts.call(project_id: args[:project_key])
  end

  desc "Import the completed transcripts from the VoiceBase api"
  task :import_transcripts_from_api => :environment do |task, args|
    Transcript.voicebase_processing_pending.not_picked_up_for_voicebase_processing.find_each do |transcript|
      VoiceBase::VoicebaseApiService.check_progress(transcript.id)
      transcript = Transcript.find(transcript.id)
      VoiceBase::VoicebaseApiService.process_transcript(transcript.id)
    end
  end
end
