namespace :voice_base do
  # Usage: rake voice_base:import_transcripts['oral-history']
  desc 'Import transcripts generated by VoiceBase'
  task :import_transcripts, [:project_key] => :environment do |task, args|
    VoiceBase::ImportSrtTranscripts.call(project_id: args[:project_key])
  end
end
