SECRET_KEY_BASE: xxx
PUA_CLIENT_ID: xxx
PUA_CLIENT_SECRET: xxx
VOICEBASE_CLIENT_ID: xxx
VOICEBASE_CLIENT_SECRET: xxx
PROJECT_ID: nsw-state-library-amplify
NEW_RELIC_LICENSE_KEY: xxx
AWS_S3_ACCESS_KEY_ID: xxx
AWS_S3_SECRET_ACCESS_KEY: xxx
<%# SAML_CONSUMER_SERVICE_URL: xxx %>
SAML_ISSUER: xxx
SAML_SSO_TARGET_URL: xxx
SAML_IDP_CERT_PATH: xxx
SAML_NAME_ID_FORMAT: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
# Used by speech-to-text.js
SPEECH_TO_TEXT_KEY: Ask admin to obtain the subscription key from Azure portal -> Cognitive Services -> Keys and Endpoint
SPEECH_TO_TEXT_REGION: Ask admin to obtain the region from Azure portal -> Cognitive Services -> Keys and Endpoint

development:
  GOOGLE_CLIENT_ID: xxx
  GOOGLE_CLIENT_SECRET: xxx
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx

production:
  GOOGLE_CLIENT_ID: xxx
  GOOGLE_CLIENT_SECRET: xxx
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx
