privacy:
  url: http://www.sl.nsw.gov.au/privacy
copyright:
  url: http://www.sl.nsw.gov.au/copyright
client_code_of_conduct:
  url: http://www.sl.nsw.gov.au/about-library-legislation-and-policies/client-code-conduct
feedback:
  url: http://www.sl.nsw.gov.au/feedback
